# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1711, 1320)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 768))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/main.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setTabletTracking(False)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 1, 0, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 2, 0, 1, 1)
        self.labelHeader = QtWidgets.QLabel(self.centralwidget)
        self.labelHeader.setText("")
        self.labelHeader.setPixmap(QtGui.QPixmap("resources/header.png"))
        self.labelHeader.setScaledContents(True)
        self.labelHeader.setObjectName("labelHeader")
        self.gridLayout.addWidget(self.labelHeader, 0, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 4)
        self.gridLayout.setRowStretch(2, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.dockWidgetLog = QtWidgets.QDockWidget(self.centralwidget)
        self.dockWidgetLog.setMinimumSize(QtCore.QSize(600, 400))
        self.dockWidgetLog.setFloating(True)
        self.dockWidgetLog.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.dockWidgetLog.setObjectName("dockWidgetLog")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plainTextEditLog = QtWidgets.QPlainTextEdit(self.dockWidgetContents)
        self.plainTextEditLog.setObjectName("plainTextEditLog")
        self.verticalLayout.addWidget(self.plainTextEditLog)
        self.dockWidgetLog.setWidget(self.dockWidgetContents)
        self.gridLayout_2.addWidget(self.dockWidgetLog, 0, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setAllowedAreas(QtCore.Qt.LeftToolBarArea)
        self.toolBar.setIconSize(QtCore.QSize(63, 63))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionSetup = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/setup.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSetup.setIcon(icon1)
        self.actionSetup.setObjectName("actionSetup")
        self.actionDisplayLog = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resources/log.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDisplayLog.setIcon(icon2)
        self.actionDisplayLog.setObjectName("actionDisplayLog")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("resources/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon3)
        self.actionExit.setObjectName("actionExit")
        self.actionImageAdjust = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("resources/imgAdjust.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImageAdjust.setIcon(icon4)
        self.actionImageAdjust.setObjectName("actionImageAdjust")
        self.actionStart = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("resources/start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStart.setIcon(icon5)
        self.actionStart.setObjectName("actionStart")
        self.actionStop = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("resources/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon6)
        self.actionStop.setObjectName("actionStop")
        self.actionPause = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("resources/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPause.setIcon(icon7)
        self.actionPause.setObjectName("actionPause")
        self.actionNext = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("resources/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNext.setIcon(icon8)
        self.actionNext.setObjectName("actionNext")
        self.actionPrev = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("resources/prev.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrev.setIcon(icon9)
        self.actionPrev.setObjectName("actionPrev")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("resources/redo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedo.setIcon(icon10)
        self.actionRedo.setObjectName("actionRedo")
        self.toolBar.addAction(self.actionSetup)
        self.toolBar.addAction(self.actionDisplayLog)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionStart)
        self.toolBar.addAction(self.actionPause)
        self.toolBar.addAction(self.actionStop)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionNext)
        self.toolBar.addAction(self.actionPrev)
        self.toolBar.addAction(self.actionRedo)
        self.toolBar.addAction(self.actionImageAdjust)
        self.toolBar.addAction(self.actionExit)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dockWidgetLog.setWindowTitle(_translate("MainWindow", "日志"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionSetup.setText(_translate("MainWindow", "设置"))
        self.actionSetup.setToolTip(_translate("MainWindow", "<html><head/><body><p>参数设置</p></body></html>"))
        self.actionDisplayLog.setText(_translate("MainWindow", "日志"))
        self.actionDisplayLog.setToolTip(_translate("MainWindow", "显示日志窗口"))
        self.actionExit.setText(_translate("MainWindow", "退出"))
        self.actionExit.setToolTip(_translate("MainWindow", "退出程序"))
        self.actionImageAdjust.setText(_translate("MainWindow", "图像调整"))
        self.actionImageAdjust.setToolTip(_translate("MainWindow", "调整图像明暗度及对比度调整"))
        self.actionStart.setText(_translate("MainWindow", "开始"))
        self.actionStart.setToolTip(_translate("MainWindow", "开始检测"))
        self.actionStop.setText(_translate("MainWindow", "停止"))
        self.actionStop.setToolTip(_translate("MainWindow", "停止检测"))
        self.actionPause.setText(_translate("MainWindow", "暂停"))
        self.actionPause.setToolTip(_translate("MainWindow", "暂停检测"))
        self.actionNext.setText(_translate("MainWindow", "下一张"))
        self.actionNext.setToolTip(_translate("MainWindow", "检测下一张图像"))
        self.actionPrev.setText(_translate("MainWindow", "上一张"))
        self.actionPrev.setToolTip(_translate("MainWindow", "检测上一张图像"))
        self.actionRedo.setText(_translate("MainWindow", "重新检测"))
        self.actionRedo.setToolTip(_translate("MainWindow", "重新检测当前图像"))
